### ISSUE TITLE
Please revert readme.md to previous version

### ISSUE THREAD

**Issue by Franky1** [Schm1tz1/arduino-tsic#5]
Please revert readme.md to previous version to avoid confusion.
My readme.md contained already the documentation for my fork.
So my readme.md doesn't fit to your library.
Sorry, was my fault...

PS: I just uploaded my version of the library, if you want to have a look.

**Comment by Schm1tz1** [comment]
Hi,

ok, just changed it back to the old version. Nice work with the 506. By the
way - I found a typo an corrected it. The method "Temperture" was missing
an "a". Maybe one could do some "unified" version if there is a way to
detect the type of sensor but that is just an idea. Does your constant
powering include any additional heat due to higher power consumption of the
sensor ? I think that was the original idea why it was turned off while not
reading.
I had such issues with a different sensor and you could really see the
systematic effect you introduce by constantly powering and/or reading it at
a high frequency. That's why I'm asking. One might introduce a systematic
offset and a slower temperature response especially when cooling down.

Cheers,
Schm1tz1

**Comment by Schm1tz1** [comment]
done.

**Comment by Franky1** [comment]
I compared my library version (permanently powered) with the original version (temporarily powered) and ran both versions for several hours parallel on two arduino boards with three Tsic506 connected to each board. All sensors were taped together with an calibrated temperature sensor. 
I could not observe any deviations between both versions in the temperature measurements, there was no "self-heating" of the Tsic's in my version.
